---
# ===============================================================
# packages: install the necessary packages
# ===============================================================

- name: Install packages
  apt: pkg={{ item }}
    state=latest
    update_cache=true
  with_items:
    - monit
  tags: packages
