---
# ===============================================================
# configure: configure monit
# ===============================================================

- include_vars: "defaults/main.yml"

- name: Configure the monitrc file
  action: template
    src=templates/monitrc.j2
    dest=/etc/monit/monitrc
    backup=yes
    mode=0600
  tags: configure
