---
# handlers file for ansible-role-monit

- name: restart monit
  sudo: yes
  service: name=monit state=restarted

- name: restart apache
  sudo: yes
  service: name=apache2 state=restarted

- name: reload apache
  sudo: yes
  service: name=apache2 state=reloaded
