---
# handlers file for ansible-role-monit

- name: restart monit
  become: yes
  service: name=monit state=restarted

- name: restart apache
  become: yes
  service: name=apache2 state=restarted

- name: reload apache
  become: yes
  service: name=apache2 state=reloaded
